### ISSUE TITLE
[Feature Request] LED status lights

### ISSUE THREAD

**Issue by NovaViper** [mainsail-crew/mainsail-config#14]
Hey, I'm wondering if it would be possible to add status lights (or the ability to define additional gcode that runs along with the macros). I typically add status macros that simply run led effects I defined with [klipper-led-effect](https://github.com/julianschill/klipper-led_effect) into the CANCEL and PAUSE macros this configuration defines and it would be really nice to not have to constantly modify the main configurations in order to add them.

**Comment by meteyou** [comment]
This is nothing for a generic config for working with Mainsail. if you just need help to setup something like this, pls use our discord server.
