### ISSUE TITLE
add unload/load Filament ?

### ISSUE THREAD

**Issue by wildwick69** [mainsail-crew/mainsail-config#15]
wouldn't it make sense to include unload/load filament and M600 here as well so all important procedures except print_start and print_end would be covered in the same place?

**Comment by zellneralex** [comment]
Unload/load filament is heavily printer depending. To make that somehow general working you would need a lot of parameters what makes it extrem hard to setup. In the most cases you are much faster to write that macro dedicated for your own printer.

For M600 many people want different park position or already include the filament unloaded and tip forming. We have a simple example in the config.
```
## Use the PAUSE macro direct in your M600:
##  e.g. with a different park position front left and a minimal height of 50 
##    [gcode_macro M600]
##    description: Filament change
##    gcode: PAUSE X=10 Y=10 Z_MIN=50
##  Z_MIN will park the toolhead at a minimum of 50 mm above to bed to make it easier for you to swap filament.
```
Also the PAUSE macro is written in a way that you could use it with other X:Y and a minimum Z distance so that adding a M600 is coping that 3 lines and modifying 3 numbers.

**Comment by wildwick69** [comment]
Hi, many thanks for your answer!!

 

Think you are right, so I already implemented the variables to my load/unload/m600 + physical buttons like this:

 

[gcode_button UNL_FILA]

pin: ^!PG12

press_gcode:

    {% if printer.idle_timeout.state == 'Printing' %}                                    ; if printing      

       PAUSE Z_MIN=50                                                                    ; goto colour change position with minimum Z 50mm or Z+2mm if above    

    {% endif %}

       UNLOAD_FILAMENT

 

[gcode_button L_FILA]

pin: ^!PG13

press_gcode:

    {% if printer.idle_timeout.state != 'Printing' or printer.pause_resume.is_paused %}  ; load only if not currently prining or print is paused

      LOAD_FILAMENT

    {% endif %}

 

[gcode_macro UNLOAD_FILAMENT]

description:Unload Filament

gcode:

    {% set change_x = printer['gcode_macro _CLIENT_VARIABLE']['custom_park_x'] %}        ; set colour change position -> mainsail-configs Variable

    {% set change_y = printer['gcode_macro _CLIENT_VARIABLE']['custom_park_y'] %}        ; set colour change position -> mainsail-configs Variable

    {% set hotendtemp = params.HOTEND|default(230)|int %}

    SAVE_GCODE_STATE NAME=unload_state

    {% if printer.pause_resume.is_paused == False %}                            ; PAUSE active? if not then normal unload with position, heatup, forming tip

      M104 S{hotendtemp}                                                        ; set & continue hotend temp, default to 230

      {% if printer.toolhead.homed_axes != 'xyz' %}                             ; Home if not already homed

        M117 Homing...

        STATUS_HOMING                                                           ; LEDs show homing

        G28                                                                     ; Alphaville: Lassie come home, come home lalala

     {% endif %}

      G1 Y{change_y} X{change_x} Z50 F6000                                      ; move toolhead to custom Park Position

      M117 Heating

      STATUS_HEATING                                                            ; LEDs show heating

      M109 S{hotendtemp}                                                        ; set & wait for hotend temp, default to 230

      M117 Unloading Filament 

      STATUS_UNLOADING                                                          ; LEDs show unloading

      G91

      G0 E15 F360                                                               ; extract a bit

      G0 E5 F3600                                                               ; blob a bit

      G0 E-22 F3600                                                             ; forming filament Tip for Rapido -> from ERCF V3 ercf_software.cfg 

      G0 E2 F300

      G0 E-2.1 F300

      G0 E2 F300

      G0 E-2.2 F300

      G0 E2 F300

      G0 E-2.3 F300

      G0 E2 F300

      G0 E-2.4 F300

      G0 E2 F300

      G0 E-2.5 F300

      G0 E2 F300

      G0 E-43 F300                                                              ; Filament Tip cooldown till extruder gears for Rapido -> from ERCF V3 ercf_software.cfg 

      G0 E-100 F3600                                                            ; aaand puke it out fast

      M117 Filament unloaded, what now?

    {% else %}                                                                  ; UUPS!! Pause or M600 active, hurry up now, time is Filament 

      M117 Unloading Filament

      STATUS_UNLOADING                                                          ; LEDs show unloading -> new status added to logo.cfg

      G91

      G0 E10 F360                                                               ; extract a bit

      G0 E5 F3600                                                               ; blob a bit

      G0 E-150 F3600                                                            ; no time for forming tip, schwupdiwup, away with it

      M117 Filament unloaded, hurry up for the next!

    {% endif %}

    G90

    M400                                                                        ; wait for moves to finish

    STATUS_READY                                                                ; LEDs show ready

    RESTORE_GCODE_STATE NAME=unload_state

 

[gcode_macro LOAD_FILAMENT]

description:Load Filament

gcode:

    {% set change_x = printer['gcode_macro _CLIENT_VARIABLE']['custom_park_x'] %}        ;set colour change position -> mainsail-configs Variable

    {% set change_y = printer['gcode_macro _CLIENT_VARIABLE']['custom_park_y'] %}        ;set colour change position -> mainsail-configs Variable

    {% set park_x = printer['gcode_macro _CLIENT_VARIABLE']['park_at_cancel_x'] %}       ;set bucket position -> mainsail-configs Variable

    {% set park_y = printer['gcode_macro _CLIENT_VARIABLE']['park_at_cancel_y'] %}       ;set bucket position -> mainsail-configs Variable

    {% set pauseretract = printer['gcode_macro _CLIENT_VARIABLE']['retract'] %}          ;set retract at pause -> mainsail-configs Variable

    {% set cancelretract = printer['gcode_macro _CLIENT_VARIABLE']['cancel_retract'] %}  ;set retract at cancel -> mainsail-configs Variable

    {% set hotendtemp = params.HOTEND|default(230)|int %}

    SAVE_GCODE_STATE NAME=load_state

    {% if printer.pause_resume.is_paused == False %}                            ; PAUSE active? if not then normal loading with position, heatup...      

      M104 S{hotendtemp}                                                        ; set & continue hotend temp, default to 230

      {% if printer.toolhead.homed_axes != 'xyz' %}                             ; Home if not already homed

        M117 Homing...

        STATUS_HOMING                                                           ; LEDs show homing

        G28                                                                     ; Lynyrd Skynyrd: sweet home Alabama Lalala

      {% endif %}

      G1 Y{change_y} X{change_x} Z50 F6000                                      ; move toolhead to custom Park Position and ...

      M117 Heating      

      STATUS_HEATING                                                            ; LEDs show heating

      M109 S{hotendtemp}                                                        ; set & wait for hotend temp, default to 230

      M117 loading Filament

      STATUS_LOADING                                                            ; LEDs show printing

      G91

      G1 E200 F360                                                              ; extract 200mm for colour change

      G1 E5 F3600                                                               ; blob for cleaning Nozzle

      G1 E-{cancelretract} F1200                                                ; retract for non oozing

      M117 Filament ready...

      M400

      STATUS_COOLING                                                            ; LEDs show cooling

#      TURN_OFF_HEATERS

      M104 S0

      G90

      G0 X{park_x} Y{park_y} Z20 F6000                                          ; park nozzle over bucket

      M400                                                                      ; wait for moves to finish

      M84

      STATUS_READY                                                              ; LEDs show Ready

      RESTORE_GCODE_STATE NAME=load_state

   {% else %}                                                                  ; UUPS!! Pause or M600 active, hurry up now, printfailure waits for you

      M117 loading Filament

      STATUS_LOADING                                                            ; LEDs show loading -> new status added to logo.cfg

      G91

      G1 E200 F360                                                              ; extract 200mm for colour change

      G1 E5 F3600                                                               ; blob for cleaning Nozzle

      G1 E-{pauseretract} F1200                                                 ; retract for non oozing

      M117 Filament ready, resuming...

      G90

      M400

      STATUS_PRINTING

      RESTORE_GCODE_STATE NAME=load_state

      RESUME

    {% endif %}

 

 

[gcode_macro M600]description: Filament change

gcode: 

    PAUSE Z_MIN=50                                                              ; goto colour change position with minimum Z 50mm or Z+2mm if above

    UNLOAD_FILAMENT

 

 

Lg, Wick

 

Von: Alex Zellner ***@***.***> 
Gesendet: Freitag, 14. April 2023 06:39
An: mainsail-crew/mainsail-config ***@***.***>
Cc: wildwick69 ***@***.***>; Author ***@***.***>
Betreff: Re: [mainsail-crew/mainsail-config] add unload/load Filament ? (Issue #15)

 

Unload/load filament is heavily printer depending. To make that somehow general working you would need a lot of parameters what makes it extrem hard to setup. In the most cases you are much faster to write that macro dedicated for your own printer.

For M600 many people want different park position or already include the filament unloaded and tip forming. We have a simple example in the config.

## Use the PAUSE macro direct in your M600:
##  e.g. with a different park position front left and a minimal height of 50 
##    [gcode_macro M600]
##    description: Filament change
##    gcode: PAUSE X=10 Y=10 Z_MIN=50
##  Z_MIN will park the toolhead at a minimum of 50 mm above to bed to make it easier for you to swap filament.

Also the PAUSE macro is written in a way that you could use it with other X:Y and a minimum Z distance so that adding a M600 is coping that 3 lines and modifying 3 numbers.
