### ISSUE TITLE
Improved at layer macros

### ISSUE THREAD

**Issue by Henk72** [mainsail-crew/mainsail-config#28]
The SET_PAUSE_AT_LAYER logic could be enhanced based on next macros: https://github.com/jschuh/klipper-macros/blob/main/layers.cfg

It also allows to also trigger on height instead of layer number. G-code commands can be scheduled as well as other easy macros to change speed and other things.

 I did not create these macros, but used them myself together with this mainsail-config with a small adjustment related to 'before layer height' and 'after layer height'

**Comment by zellneralex** [comment]
The mainsail.cfg should give you an easy start on your Klipper printer, and should be easy to configure, I am only took a short look at the link but it looks to me that you need also of slicer setups. The example might work perfect at PS or SuSi but not on all others.
