### ISSUE TITLE
Imbalance between _CLIENT_RETRACT and _CLIENT_EXTRUDE

### ISSUE THREAD

**Issue by sk8board** [mainsail-crew/mainsail-config#34]
### Problem Description

When using Firmware Retract with mainsail.cfg, Pause and Resume, the extruder will over extrude during Resume.

### Cause

The mainsail.cfg macro, _CLIENT_EXTRUDE, supports Firmware Retract while _CLIENT_RETRACT does not support Firmware Retract.

### Example

If Firmware Retract is set to 10mm retract but the _CLIENT_VARIABLE is set to default 1mm, then _CLIENT_EXTRUDE will over-extrude by 9mm because _CLIENT_RETRACT does not support Firmware Retract.

### Recommended Solution

Add Firmware Retract to _CLIENT_RETRACT

_CLIENT_VARIABLE
![image](https://github.com/user-attachments/assets/858be9e4-6dec-41e6-bb4e-d153d28572ad)

_CLIENT_EXTRUDE
![image](https://github.com/user-attachments/assets/4b17fda9-329d-4a72-8e8d-a30282bf5e70)

_CLIENT_RETRACT
![image](https://github.com/user-attachments/assets/6fe2f1ce-a614-42e4-a9be-0b993b60264e)

**Comment by flowerysong** [comment]
As you can see in your screenshot `_CLIENT_RETRACT` calls `_CLIENT_EXTRUDE`, so it supports exactly the same things that `_CLIENT_EXTRUDE` does.

**Comment by sk8board** [comment]
Please note that I understand lines 268 through 273 should be used when retracting, but there is a problem of severe over extrusion during Resume.

**Comment by flowerysong** [comment]
If you understand that `_CLIENT_RETRACT` supports firmware retraction, why does this bug report exist?

**Comment by sk8board** [comment]
I have verified `[firmware_retraction]` has `unretract_extra_length` set to zero.

**Comment by meteyou** [comment]
@sk8board pls close this issue, when all questions are answered.

**Comment by sk8board** [comment]
I believe I know what is my problem, let me explain.

- At the end of a PAUSE, I have a macro drive the nozzle to the bed, Z=0.000, to prevent the nozzle from oozing while paused. 
- While the nozzle is at the bed, filament is oozing to the bottom of the nozzle but cannot escape.  
- This results in an air pocket between the oozed filament at the bottom and the solid filament above.
- When un-retracting G11 (15mm), the air pocket does not allow the filament to fully unretract which causes the extruder gears to skip on the filament.

Does this sound reasonable, or could there be a problem with the PAUSE and RESUME macros?

**Comment by meteyou** [comment]
@sk8board if you have only issues with your gcode, pls use your discord server or the discussions section on github. the issue tracker is no place for help. we try to track real bugs and features with it.

**Comment by sk8board** [comment]
@meteyou If you read this issue, you can see this is not a problem with my gcode.

**Comment by meteyou** [comment]
i read it and your issue has nothing todo with the mainsail-config macros. its just your usecase and your gcode. so pls stop spamming this issue tracker here...
