### ISSUE TITLE
Different parking positions

### ISSUE THREAD

**Issue by stenmic** [mainsail-crew/mainsail-config#4]
Hi,
with the variables in Customize macros I can define the parking position for X and Y.
I would like to have different positions for PAUSE and CANCEL_PRINT. e.g.

#########################################################################
[gcode_macro _CLIENT_VARIABLE]
variable_use_custom_pos  : True  ; use custom park coordinates for x,y [True/False] 
variable_custom_park_x_pause   : -5.0 ; custom x position; value must be within your defined min and max of X
variable_custom_park_y_pause   : -5.0  ; custom y position; value must be within your defined min and max of Y
variable_custom_park_x_cancel   : -5.0 ; custom x position; value must be within your defined min and max of X
variable_custom_park_y_cancel   : 250.0  ; custom y position; value must be within your defined min and max of Y
variable_custom_park_dz  : 2.0   ; custom dz value; the value in mm to lift the nozzle when move to park position 
variable_retract         : 1.0   ; the value to retract while PAUSE
variable_cancel_retract  : 5.0   ; the value to retract while CANCEL_PRINT
variable_speed_retract   : 35.0  ; retract speed in mm/s
variable_unretract       : 1.0   ; the value to unretract while RESUME
variable_speed_unretract : 35.0  ; unretract speed in mm/s
variable_speed_hop       : 15.0  ; z move speed in mm/s
variable_speed_move      : 100.0 ; move speed in mm/s
#variable_use_fw_retract  : False ; use fw_retraction instead of the manual version [True/False] 
gcode:
#########################################################################

**Comment by zellneralex** [comment]
Can you explain why you need that. If we talking about an M600 then look at https://github.com/mainsail-crew/mainsail-config/blob/master/mainsail.cfg#L33.

**Comment by stenmic** [comment]
Not for M600. but for the buttons in mainsail. pause and stop
![C0A20417-9D65-400A-BDB0-01F861973FA6](https://user-images.githubusercontent.com/56360313/216805485-9a8e5ff6-febb-4c3b-a417-39004a4548ac.jpeg)

**Comment by zellneralex** [comment]
I still wonder, why you need that? So what is your workflow that needs separate park position for pause and cancel. From your values I assume you using a delta, so what is the motivation to have the tool head nearly in the middle while pause and mid-back while cancel. Why not using the mid-back position in both cases.
 Don’t get me wrong the change is doable but I want to understand the motivation behind it before I add more complexity to the setup by adding at least 3 more parameter.

**Comment by zellneralex** [comment]
I have a change in the pipe that will add a feature like that.

**Comment by stenmic** [comment]
When I press pause in Mainsail, the best position for the bed is at the back.

![520E332E-613E-4B74-9C22-887FA520EC63](https://user-images.githubusercontent.com/56360313/220904242-4ac4e52e-2128-40be-a3f6-9a65ab45bb51.jpeg)

when i stop the print  the best position for the bed is at the front. I can't describe it better :)

![E2FD2101-9068-4FB3-82C5-5910F2838E9A](https://user-images.githubusercontent.com/56360313/220904291-f03c51ad-f2c4-44ce-b6d9-44cbd459ccb6.jpeg)

**Comment by zellneralex** [comment]
Thanks for the description, as said I have that feature in the pipe but need to wait for the open PR to merge. I will link the merge here when it is done.

**Comment by stenmic** [comment]
that's great

**Comment by zellneralex** [comment]
Feature added in https://github.com/mainsail-crew/mainsail-config/commit/7f7cb7b09802a086cf1f4c946ef7055047e9011f
