### ISSUE TITLE
Spelling and Syntax Corrrections

### ISSUE THREAD

**Issue by GDRPrint** [mainsail-crew/mainsail-config#5]
"But doing it is simple copy and paste a few commands in an ssh terminal. The instructions assume that you have a up to data and working moonraker installation. If not start with updating your moonraker first."

Change that you have a to an

"You need to update your moonraker.conf to get alway the latest version"

Change get alway to always get

"than open your moonraker.conf and add"

Change than to then

"for that simple copy the [virtual_sdcard] block from the mainsail.cfg and simple place it below your include. The result should look similar to:"

Change both simple to simply

"The values are the same as the used default."

Change used to user

**Comment by zellneralex** [comment]
Thank you, I integrated your suggestions in de7ea7ecd8b2a382af94ef09e91551b530d96b35
